version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 8080:80
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
     - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-flask
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "5001:5001"
    command: python app.py
